
service: my-serverless-app

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1  
  stage: dev

plugins:
  - serverless-iam-roles-per-function

functions:
  apiGatewayTrigger:
    handler: handler.apiGatewayTrigger
    events:
      - http:
          path: /
          method: any

resources:
  Resources:
    MyStateMachineeeee:
      Type: AWS::StepFunctions::StateMachine
      Properties:
        DefinitionString: |-
          {
            "Comment": "New Step function to execute the first state of the existing state machine",
            "StartAt": "ExecuteFirstState",
            "States": {
              "ExecuteFirstState": {
              "Type": "Task",
              "Resource": "arn:aws:lambda:us-east-1:113925753635:function:my-serverless-app-dev-apiGatewayTrigger",
              "End": true
               }
            }
          }
        RoleArn: 'arn:aws:iam::113925753635:role/MyStateMachine'